# 部署時執行的指令，--minify壓縮HTML，--gc自動在建置後刪除快取檔案
[build]
  publish = "public"
  command = "hugo --gc --minify"

# 指定Hugo版本，應與本機安裝的Hugo版本一致
[build.environment]
  HUGO_VERSION = "v0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended"
